"use client";

import Link from "next/link";
import { useState, type ReactNode } from "react";
import { ESTADOS_ORDEN, type OrdenDetalle } from "@/lib/operacion-modelos";
import { EstadoBadge, formatearDinero, Icono } from "./elementos-operacion";

type Seccion = "resumen" | "servicios" | "repuestos" | "pagos" | "historial" | "seguimiento";
const secciones: Array<{ id: Seccion; etiqueta: string; icono: Parameters<typeof Icono>[0]["nombre"] }> = [
  { id: "resumen", etiqueta: "Resumen", icono: "archivo" },
  { id: "servicios", etiqueta: "Servicios", icono: "servicio" },
  { id: "repuestos", etiqueta: "Repuestos", icono: "pieza" },
  { id: "pagos", etiqueta: "Pagos", icono: "pago" },
  { id: "historial", etiqueta: "Historial", icono: "historial" },
  { id: "seguimiento", etiqueta: "Seguimiento", icono: "enlace" },
];

function Caja({ titulo, accion, children }: { titulo: string; accion?: ReactNode; children: ReactNode }) {
  return <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm dark:border-stone-800 dark:bg-stone-900 sm:p-6"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="font-bold text-stone-950 dark:text-white">{titulo}</h2>{accion}</div>{children}</section>;
}

function BotonAgregar({ children }: { children: ReactNode }) {
  return <button type="button" className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-stone-200 px-3 text-xs font-bold text-teal-700 hover:bg-teal-50 dark:border-stone-700 dark:text-teal-400 dark:hover:bg-teal-950"><Icono nombre="mas" className="size-3.5" />{children}</button>;
}

function ModalConfirmacion({ titulo, descripcion, requiereMotivo, peligro, onClose }: { titulo: string; descripcion: string; requiereMotivo?: boolean; peligro?: boolean; onClose: () => void }) {
  return <div role="presentation" className="fixed inset-0 z-50 grid place-items-center bg-stone-950/60 p-4 backdrop-blur-sm" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div role="dialog" aria-modal="true" aria-labelledby="titulo-dialogo" className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl dark:bg-stone-900"><span className={`grid size-10 place-items-center rounded-xl ${peligro ? "bg-red-50 text-red-700 dark:bg-red-950" : "bg-amber-100 text-amber-800 dark:bg-amber-950"}`}><Icono nombre="alerta" /></span><h2 id="titulo-dialogo" className="mt-4 text-lg font-bold text-stone-950 dark:text-white">{titulo}</h2><p className="mt-2 text-sm text-stone-600 dark:text-stone-300">{descripcion}</p>{requiereMotivo && <label className="mt-4 block"><span className="mb-1.5 block text-xs font-semibold">Motivo *</span><textarea autoFocus required rows={3} className="w-full resize-y rounded-xl border border-stone-200 bg-stone-50 p-3 text-sm outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-500/15 dark:border-stone-700 dark:bg-stone-950" placeholder="Describe el motivo para dejar trazabilidad…" /></label>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="min-h-10 rounded-xl px-4 text-sm font-semibold text-stone-600 hover:bg-stone-100 dark:text-stone-300 dark:hover:bg-stone-800">Cancelar</button><button type="button" onClick={onClose} className={`min-h-10 rounded-xl px-4 text-sm font-bold text-white ${peligro ? "bg-red-700 hover:bg-red-600" : "bg-teal-800 hover:bg-teal-700"}`}>Confirmar</button></div></div></div>;
}

function Resumen({ orden }: { orden: OrdenDetalle }) {
  return <div className="grid gap-5 lg:grid-cols-2">
    <Caja titulo="Información del equipo" accion={<button type="button" className="grid size-8 place-items-center rounded-lg text-stone-400 hover:bg-stone-100 hover:text-teal-700 dark:hover:bg-stone-800" aria-label="Editar equipo"><Icono nombre="editar" className="size-4" /></button>}><dl className="grid gap-x-4 gap-y-4 text-sm sm:grid-cols-2"><div><dt className="text-xs text-stone-400">Equipo</dt><dd className="mt-1 font-semibold">{orden.equipo}</dd></div><div><dt className="text-xs text-stone-400">Referencia</dt><dd className="mt-1 font-semibold">{orden.referenciaEquipo}</dd></div><div><dt className="text-xs text-stone-400">Serial / IMEI</dt><dd className="mt-1 font-mono text-xs font-semibold">{orden.serial}</dd></div><div><dt className="text-xs text-stone-400">Garantía</dt><dd className="mt-1 font-semibold">{orden.garantiaDias} días</dd></div><div className="sm:col-span-2"><dt className="text-xs text-stone-400">Accesorios y estado de ingreso</dt><dd className="mt-1 text-stone-700 dark:text-stone-300">{orden.accesorios}</dd></div></dl></Caja>
    <Caja titulo="Cliente"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-teal-50 font-bold text-teal-700 dark:bg-teal-950 dark:text-teal-300">MG</span><div><p className="font-semibold">{orden.cliente}</p><p className="text-xs text-stone-500">{orden.telefonoCliente}</p></div></div><p className="mt-4 text-sm text-stone-500 dark:text-stone-400">{orden.correoCliente}</p></Caja>
    <Caja titulo="Falla reportada"><p className="text-sm leading-6 text-stone-700 dark:text-stone-300">{orden.falla}</p></Caja>
    <Caja titulo="Diagnóstico" accion={<button type="button" className="text-xs font-bold text-teal-700 hover:underline dark:text-teal-400">Editar</button>}><p className="text-sm leading-6 text-stone-700 dark:text-stone-300">{orden.diagnostico || "Aún no se ha registrado un diagnóstico."}</p></Caja>
    <div className="lg:col-span-2"><Caja titulo="Trabajo realizado" accion={<button type="button" className="text-xs font-bold text-teal-700 hover:underline dark:text-teal-400">Actualizar</button>}><p className="text-sm leading-6 text-stone-700 dark:text-stone-300">{orden.trabajoRealizado || "Aún no hay trabajo realizado."}</p></Caja></div>
  </div>;
}

function Lineas({ orden, tipo }: { orden: OrdenDetalle; tipo: "servicios" | "repuestos" }) {
  const lineas = orden[tipo];
  return <Caja titulo={tipo === "servicios" ? "Servicios de la orden" : "Repuestos utilizados"} accion={<BotonAgregar>Agregar {tipo === "servicios" ? "servicio" : "repuesto"}</BotonAgregar>}>
    {lineas.length ? <div className="divide-y divide-stone-100 dark:divide-stone-800">{lineas.map((linea) => <div key={linea.id} className="grid grid-cols-[1fr_auto] gap-4 py-4 first:pt-0 last:pb-0"><div><p className="text-sm font-semibold text-stone-900 dark:text-white">{linea.concepto}</p><p className="mt-1 text-xs text-stone-500">{linea.detalle} · Cantidad: {linea.cantidad}</p></div><div className="text-right"><p className="text-sm font-bold tabular-nums">{formatearDinero(linea.total)}</p><button type="button" className="mt-1 text-xs font-semibold text-red-600 hover:underline dark:text-red-400">Retirar</button></div></div>)}</div> : <p className="rounded-xl bg-stone-50 p-8 text-center text-sm text-stone-500 dark:bg-stone-950">Todavía no hay {tipo} en esta orden.</p>}
  </Caja>;
}

function Pagos({ orden, confirmar }: { orden: OrdenDetalle; confirmar: (titulo: string, descripcion: string) => void }) {
  return <Caja titulo="Pagos registrados" accion={<BotonAgregar>Registrar pago</BotonAgregar>}><div className="mb-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-stone-50 p-4 dark:bg-stone-950"><p className="text-xs text-stone-500">Total</p><p className="mt-1 font-bold tabular-nums">{formatearDinero(orden.total)}</p></div><div className="rounded-xl bg-emerald-50 p-4 dark:bg-emerald-950/40"><p className="text-xs text-emerald-700 dark:text-emerald-400">Pagado</p><p className="mt-1 font-bold tabular-nums text-emerald-800 dark:text-emerald-200">{formatearDinero(orden.pagado)}</p></div><div className="rounded-xl bg-amber-50 p-4 dark:bg-amber-950/40"><p className="text-xs text-amber-700 dark:text-amber-400">Saldo</p><p className="mt-1 font-bold tabular-nums text-amber-900 dark:text-amber-200">{formatearDinero(orden.saldo)}</p></div></div>{orden.pagos.length ? <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-stone-200 text-xs text-stone-500 dark:border-stone-700"><tr><th className="py-3">Fecha</th><th className="py-3">Método</th><th className="py-3">Referencia</th><th className="py-3 text-right">Importe</th><th className="py-3 text-right">Acción</th></tr></thead><tbody>{orden.pagos.map((pago) => <tr key={pago.id} className="border-b border-stone-100 last:border-0 dark:border-stone-800"><td className="py-4">{pago.fecha}</td><td className="py-4 font-semibold">{pago.metodo}</td><td className="py-4 font-mono text-xs text-stone-500">{pago.referencia}</td><td className="py-4 text-right font-bold tabular-nums">{formatearDinero(pago.importe)}</td><td className="py-4 text-right"><button type="button" onClick={() => confirmar("Anular pago", "El saldo será actualizado por el backend y la anulación quedará en el historial.")} className="text-xs font-semibold text-red-600 hover:underline dark:text-red-400">Anular</button></td></tr>)}</tbody></table></div> : <p className="rounded-xl bg-stone-50 p-8 text-center text-sm text-stone-500 dark:bg-stone-950">No hay pagos registrados.</p>}</Caja>;
}

function Historial({ orden }: { orden: OrdenDetalle }) {
  return <Caja titulo="Historial de la orden"><ol className="relative ml-2 border-l border-stone-200 dark:border-stone-700">{orden.historial.map((evento) => <li key={evento.id} className="relative ml-6 pb-7 last:pb-0"><span className="absolute -left-[31px] top-0.5 size-3 rounded-full border-2 border-white bg-teal-600 ring-2 ring-teal-100 dark:border-stone-900 dark:ring-teal-950" /><time className="text-xs text-stone-400">{evento.fecha}</time><h3 className="mt-1 text-sm font-bold">{evento.titulo}</h3><p className="mt-1 text-sm text-stone-600 dark:text-stone-300">{evento.descripcion}</p><p className="mt-1 text-xs text-stone-400">Por {evento.autor}</p></li>)}</ol></Caja>;
}

function Seguimiento({ orden, confirmar }: { orden: OrdenDetalle; confirmar: (titulo: string, descripcion: string) => void }) {
  return <Caja titulo="Seguimiento para el cliente"><div className={`rounded-xl border p-5 ${orden.seguimientoHabilitado ? "border-emerald-200 bg-emerald-50 dark:border-emerald-900 dark:bg-emerald-950/30" : "border-stone-200 bg-stone-50 dark:border-stone-700 dark:bg-stone-950"}`}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${orden.seguimientoHabilitado ? "bg-emerald-500" : "bg-stone-400"}`} /><p className="font-bold">{orden.seguimientoHabilitado ? "Enlace activo" : "Seguimiento desactivado"}</p></div><p className="mt-1 text-sm text-stone-600 dark:text-stone-300">{orden.seguimientoHabilitado ? "El cliente puede consultar el avance sin iniciar sesión." : "Habilítalo para compartir el estado de esta orden."}</p></div><button type="button" className="min-h-10 rounded-xl bg-teal-800 px-4 text-sm font-bold text-white hover:bg-teal-700">{orden.seguimientoHabilitado ? "Copiar enlace" : "Habilitar"}</button></div>{orden.seguimientoHabilitado && <div className="mt-5 flex flex-wrap gap-2 border-t border-emerald-200 pt-4 dark:border-emerald-900"><button type="button" onClick={() => confirmar("Rotar enlace", "El enlace actual dejará de funcionar y se generará uno nuevo.")} className="text-xs font-bold text-teal-700 hover:underline dark:text-teal-400">Rotar enlace</button><span aria-hidden="true" className="text-stone-300">·</span><button type="button" onClick={() => confirmar("Revocar seguimiento", "El cliente perderá inmediatamente el acceso al seguimiento.")} className="text-xs font-bold text-red-600 hover:underline dark:text-red-400">Revocar acceso</button></div>}</div><div className="mt-4 flex gap-3 rounded-xl bg-sky-50 p-4 text-sm text-sky-900 dark:bg-sky-950/40 dark:text-sky-200"><Icono nombre="alerta" className="mt-0.5 size-4 shrink-0" /><p>La vista pública nunca incluye pagos, métodos, costos, proveedores, IDs internos ni precios unitarios.</p></div></Caja>;
}

export function DetalleOrden({ orden, tallerId }: { orden: OrdenDetalle; tallerId: string }) {
  const [seccion, setSeccion] = useState<Seccion>("resumen");
  const [modal, setModal] = useState<{ titulo: string; descripcion: string; motivo?: boolean; peligro?: boolean } | null>(null);
  const saldoPendiente = !/^0+(\.0+)?$/.test(orden.saldo.valor);
  const confirmar = (titulo: string, descripcion: string) => setModal({ titulo, descripcion, motivo: true, peligro: true });
  function contenido() {
    if (seccion === "resumen") return <Resumen orden={orden} />;
    if (seccion === "servicios" || seccion === "repuestos") return <Lineas orden={orden} tipo={seccion} />;
    if (seccion === "pagos") return <Pagos orden={orden} confirmar={confirmar} />;
    if (seccion === "historial") return <Historial orden={orden} />;
    return <Seguimiento orden={orden} confirmar={confirmar} />;
  }
  return <>
    <div className="border-b border-stone-200 bg-white dark:border-stone-800 dark:bg-stone-900"><div className="mx-auto max-w-[1500px] px-4 py-5 sm:px-6 lg:px-8"><Link href={`/t/${tallerId}/ordenes`} className="inline-flex items-center gap-1 text-xs font-semibold text-stone-500 hover:text-teal-700 dark:text-stone-400"><Icono nombre="flecha" className="size-3.5 rotate-180" />Volver a órdenes</Link><div className="mt-4 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-bold tracking-tight text-stone-950 dark:text-white">{orden.numero}</h1><EstadoBadge estado={orden.estado} /></div><p className="mt-1.5 text-sm text-stone-500">{orden.cliente} · {orden.equipo}</p></div><div className="flex flex-wrap gap-2">{orden.estado === "entregado" && <button type="button" onClick={() => setModal({ titulo: "Reabrir por garantía", descripcion: "La orden volverá al flujo operativo y el comprobante público dejará de estar disponible.", motivo: true })} className="min-h-10 rounded-xl border border-stone-200 px-4 text-sm font-bold text-stone-700 hover:bg-stone-50 dark:border-stone-700 dark:text-stone-200 dark:hover:bg-stone-800">Reabrir por garantía</button>}{orden.transicionesPermitidas.map((estado) => { const bloqueada = estado === "entregado" && saldoPendiente; return <button key={estado} type="button" disabled={bloqueada} title={bloqueada ? "Registra el saldo pendiente antes de entregar" : undefined} onClick={() => setModal({ titulo: `Cambiar a ${ESTADOS_ORDEN[estado].etiqueta}`, descripcion: `Se registrará la transición desde ${ESTADOS_ORDEN[orden.estado].etiqueta}.`, peligro: estado === "cancelado", motivo: estado === "cancelado" })} className="min-h-10 rounded-xl bg-teal-800 px-4 text-sm font-bold text-white hover:bg-teal-700 disabled:cursor-not-allowed disabled:bg-stone-200 disabled:text-stone-500 dark:disabled:bg-stone-800">{bloqueada ? "Saldo pendiente" : `Marcar ${ESTADOS_ORDEN[estado].etiqueta.toLocaleLowerCase("es")}`}</button>; })}</div></div>{saldoPendiente && orden.estado === "listo" && <div className="mt-4 flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-900 dark:bg-amber-950/50 dark:text-amber-200"><Icono nombre="alerta" className="size-4 shrink-0" />La entrega está bloqueada hasta que el backend reporte saldo cero.</div>}</div></div>
    <div className="mx-auto grid w-full max-w-[1500px] gap-6 px-4 py-6 sm:px-6 lg:grid-cols-[minmax(0,1fr)_280px] lg:px-8 lg:py-8"><main><nav className="mb-5 flex gap-1 overflow-x-auto rounded-xl border border-stone-200 bg-white p-1 shadow-sm dark:border-stone-800 dark:bg-stone-900" aria-label="Secciones de la orden">{secciones.map((item) => <button key={item.id} type="button" onClick={() => setSeccion(item.id)} aria-current={seccion === item.id ? "page" : undefined} className={`inline-flex min-h-10 shrink-0 items-center gap-2 rounded-lg px-3 text-xs font-semibold transition ${seccion === item.id ? "bg-teal-950 text-white dark:bg-teal-700" : "text-stone-500 hover:bg-stone-100 dark:text-stone-400 dark:hover:bg-stone-800"}`}><Icono nombre={item.icono} className="size-3.5" />{item.etiqueta}</button>)}</nav>{contenido()}</main><aside className="space-y-4 lg:sticky lg:top-6 lg:self-start"><section className="rounded-2xl bg-teal-950 p-5 text-white shadow-sm dark:bg-teal-900"><p className="text-xs font-medium text-teal-200">Resumen financiero</p><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-3"><dt className="text-teal-200">Total</dt><dd className="font-bold tabular-nums">{formatearDinero(orden.total)}</dd></div><div className="flex justify-between gap-3"><dt className="text-teal-200">Pagado</dt><dd className="font-bold tabular-nums text-emerald-300">{formatearDinero(orden.pagado)}</dd></div><div className="border-t border-white/15 pt-3"><div className="flex justify-between gap-3"><dt className="font-semibold">Saldo</dt><dd className="text-lg font-bold tabular-nums text-amber-300">{formatearDinero(orden.saldo)}</dd></div></div></dl><button type="button" onClick={() => setSeccion("pagos")} className="mt-5 min-h-10 w-full rounded-xl bg-amber-400 text-sm font-bold text-amber-950 hover:bg-amber-300">Registrar pago</button></section><section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm dark:border-stone-800 dark:bg-stone-900"><h2 className="text-sm font-bold">Control de la orden</h2><dl className="mt-4 space-y-3 text-xs"><div className="flex justify-between gap-3"><dt className="text-stone-500">Última actividad</dt><dd className="font-semibold">{orden.actualizada}</dd></div><div className="flex justify-between gap-3"><dt className="text-stone-500">Servicios</dt><dd className="font-semibold">{orden.servicios.length}</dd></div><div className="flex justify-between gap-3"><dt className="text-stone-500">Repuestos</dt><dd className="font-semibold">{orden.repuestos.length}</dd></div><div className="flex justify-between gap-3"><dt className="text-stone-500">Seguimiento</dt><dd className={`font-semibold ${orden.seguimientoHabilitado ? "text-emerald-600" : "text-stone-500"}`}>{orden.seguimientoHabilitado ? "Activo" : "Inactivo"}</dd></div></dl></section></aside></div>
    {modal && <ModalConfirmacion {...modal} onClose={() => setModal(null)} />}
  </>;
}
