"use client";

import { FormEvent, useState, useTransition } from "react";
import { agregarMiembroReal, actualizarCatalogoReal, actualizarMetodoPagoReal, actualizarTallerReal, cambiarRolMiembroReal, crearCatalogoReal, crearMetodoPagoReal, retirarMiembroReal } from "@/app/gestion-actions";
import type { components } from "@/lib/api/schema";
import type { RolTaller } from "./types";
import { Icon, PageHeading, Panel, PrimaryButton, SecondaryButton, fieldClass, labelClass } from "./ui";

type Seccion = "taller" | "catalogos" | "pagos" | "miembros";
export type Catalogo = { clave?: string; titulo: string; descripcion: string; valores: string[]; items?: Array<{ id: string; nombre: string; activo: boolean; tipo_id?: string; marca_id?: string }> };
export type MetodoGestion = { id: string; nombre: string; activo: boolean };
export type MiembroGestion = { id: string; usuarioId: string; rol: "dueno" | "tecnico" };

const secciones: { id: Seccion; label: string; icon: "store" | "tag" | "card" | "shield" }[] = [
  { id: "taller", label: "Datos del taller", icon: "store" },
  { id: "catalogos", label: "Catálogos", icon: "tag" },
  { id: "pagos", label: "Métodos de pago", icon: "card" },
  { id: "miembros", label: "Miembros y roles", icon: "shield" },
];

const catalogosIniciales: Catalogo[] = [
  { titulo: "Tipos de equipo", descripcion: "Clasifica los dispositivos que recibes.", valores: ["Celular", "Portátil", "Tablet", "Consola"] },
  { titulo: "Marcas", descripcion: "Marcas disponibles al registrar un equipo.", valores: ["Apple", "Samsung", "Lenovo", "Dell", "Xiaomi"] },
  { titulo: "Tipos de servicio", descripcion: "Servicios reutilizables al cotizar una orden.", valores: ["Diagnóstico", "Cambio de pantalla", "Mantenimiento", "Recuperación de datos"] },
];

export function ConfiguracionPanel({ tallerId, rolActual = "dueno", initialCatalogos, initialMetodos, initialMiembros, nombreTaller, paisCodigo, monedaCodigo }: { tallerId: string; rolActual?: RolTaller; initialCatalogos?: Catalogo[]; initialMetodos?: MetodoGestion[]; initialMiembros?: MiembroGestion[]; nombreTaller?: string; paisCodigo?: string; monedaCodigo?: string }) {
  const esDueno = rolActual === "dueno";
  const [seccion, setSeccion] = useState<Seccion>("taller");
  const esDemo = tallerId === "demo";
  const [catalogos, setCatalogos] = useState(initialCatalogos ?? (esDemo ? catalogosIniciales : []));
  const [metodos, setMetodos] = useState<MetodoGestion[]>(initialMetodos ?? (esDemo ? [{ id: "m1", nombre: "Efectivo", activo: true }, { id: "m2", nombre: "Transferencia bancaria", activo: true }] : []));
  const [miembros, setMiembros] = useState<MiembroGestion[]>(initialMiembros ?? []);
  const [aviso, setAviso] = useState("");
  const [pendiente, iniciar] = useTransition();

  function guardar(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (esDemo) { setAviso("Cambios guardados correctamente."); return; } const data = new FormData(event.currentTarget); iniciar(async () => { try { await actualizarTallerReal(tallerId, { nombre: String(data.get("nombre") ?? ""), pais_codigo: String(data.get("pais") ?? ""), moneda_codigo: String(data.get("moneda") ?? "") }); setAviso("Cambios guardados correctamente."); } catch (error) { setAviso(error instanceof Error ? error.message : "No se pudieron guardar los cambios."); } }); }
  function agregarValor(indice: number) { const catalogo = catalogos[indice]; const valor = window.prompt(`Nuevo valor para ${catalogo.titulo}`)?.trim(); if (!valor) return; const clave = catalogo.clave; if (esDemo || !clave) { setCatalogos((actuales) => actuales.map((item, i) => i === indice ? { ...item, valores: [...item.valores, valor] } : item)); return; } iniciar(async () => { try { let datos: Record<string, unknown> = { nombre: valor }; if (clave === "modelos") { const refs = window.prompt("Escribe tipo_id y marca_id separados por | (consulta los IDs en la API)")?.split("|").map((item) => item.trim()); if (!refs || refs.length !== 2) return; datos = { nombre: valor, tipo_id: refs[0], marca_id: refs[1] }; } if (clave === "servicios") datos = { nombre: valor, descripcion: null, precio_predeterminado: "0" }; const nuevo = await crearCatalogoReal(tallerId, clave, datos) as { id: string; nombre: string; activo: boolean; tipo_id?: string; marca_id?: string }; setCatalogos((actuales) => actuales.map((item, i) => i === indice ? { ...item, valores: [...item.valores, nuevo.nombre], items: [...(item.items ?? []), nuevo] } : item)); setAviso("Valor creado correctamente."); } catch (error) { setAviso(error instanceof Error ? error.message : "No se pudo crear el valor."); } }); }
  function alternarCatalogo(catalogo: Catalogo, item: { id: string; activo: boolean }) { if (esDemo || !catalogo.clave) return; iniciar(async () => { try { if (item.activo) await actualizarCatalogoReal(tallerId, catalogo.clave!, item.id, { activo: false }); else await actualizarCatalogoReal(tallerId, catalogo.clave!, item.id, { activo: true }); setCatalogos((actuales) => actuales.map((actual) => actual === catalogo ? { ...actual, items: actual.items?.map((valor) => valor.id === item.id ? { ...valor, activo: !valor.activo } : valor) } : actual)); } catch (error) { setAviso(error instanceof Error ? error.message : "No se pudo actualizar el catálogo."); } }); }

  const navegacion = secciones.filter((item) => item.id !== "miembros" || esDueno);
  return <div className="space-y-6"><PageHeading eyebrow="Administración" title="Configuración" description="Personaliza la información y los catálogos operativos de este taller."/>
    {aviso && <div role="status" className="flex items-center justify-between rounded-xl border border-teal-200 bg-teal-50 px-4 py-3 text-sm text-teal-900 dark:border-teal-800 dark:bg-teal-950/40 dark:text-teal-200"><span>{aviso}</span><button type="button" onClick={() => setAviso("")} aria-label="Ocultar aviso"><Icon name="close" className="size-4"/></button></div>}
    <div className="grid gap-5 lg:grid-cols-[240px_minmax(0,1fr)]"><Panel className="h-fit p-2"><nav aria-label="Secciones de configuración" className="flex gap-1 overflow-x-auto lg:flex-col">{navegacion.map((item) => <button type="button" key={item.id} onClick={() => setSeccion(item.id)} aria-current={seccion === item.id ? "page" : undefined} className={`inline-flex min-w-max items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold transition lg:w-full ${seccion === item.id ? "bg-teal-50 text-teal-800 dark:bg-teal-500/10 dark:text-teal-300" : "text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-slate-800"}`}><Icon name={item.icon} className="size-4"/>{item.label}</button>)}</nav></Panel>
      <div>
        {seccion === "taller" && <Panel><div className="border-b border-slate-200 p-5 dark:border-slate-800"><h2 className="font-bold text-slate-950 dark:text-white">Información del taller</h2><p className="mt-1 text-sm text-slate-500">Estos datos identifican tu operación.</p></div><form onSubmit={guardar} className="space-y-5 p-5"><label className={labelClass}>Nombre comercial *<input name="nombre" className={fieldClass} defaultValue={nombreTaller ?? (esDemo ? "Taller Norte" : "")} required/></label><div className="grid gap-4 sm:grid-cols-2"><label className={labelClass}>País<select name="pais" className={fieldClass} defaultValue={paisCodigo ?? "CO"}><option value="CO">Colombia</option><option value="MX">México</option><option value="ES">España</option></select></label><label className={labelClass}>Moneda<select name="moneda" className={fieldClass} defaultValue={monedaCodigo ?? "COP"}><option value="COP">COP — Peso colombiano</option><option value="USD">USD — Dólar</option><option value="MXN">MXN — Peso mexicano</option></select></label></div><div className="flex justify-end"><PrimaryButton type="submit" disabled={pendiente}>{pendiente ? "Guardando…" : "Guardar cambios"}</PrimaryButton></div></form></Panel>}
        {seccion === "catalogos" && <div className="space-y-4"><div><h2 className="font-bold text-slate-950 dark:text-white">Catálogos operativos</h2><p className="mt-1 text-sm text-slate-500">Los valores inactivos permanecen en el historial.</p></div>{catalogos.map((catalogo, indice) => <Panel key={catalogo.titulo} className="p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-bold text-slate-900 dark:text-white">{catalogo.titulo}</h3><p className="mt-1 text-sm text-slate-500">{catalogo.descripcion}</p></div><SecondaryButton onClick={() => agregarValor(indice)}><Icon name="plus" className="size-4"/>Agregar</SecondaryButton></div><div className="mt-4 flex flex-wrap gap-2">{(catalogo.items ?? catalogo.valores.map((nombre, id) => ({ id: String(id), nombre, activo: true }))).map((item) => <span key={item.id} className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm ${item.activo ? "border-slate-200 bg-slate-50 text-slate-700 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200" : "border-slate-200 bg-slate-100 text-slate-400 line-through"}`}>{item.nombre}<button type="button" onClick={() => alternarCatalogo(catalogo, item)} aria-label={`${item.activo ? "Desactivar" : "Activar"} ${item.nombre}`} className="text-slate-400 hover:text-teal-600"><Icon name="edit" className="size-3.5"/></button></span>)}</div></Panel>)}</div>}
        {seccion === "pagos" && <Panel><div className="flex items-start justify-between gap-3 border-b border-slate-200 p-5 dark:border-slate-800"><div><h2 className="font-bold text-slate-950 dark:text-white">Métodos de pago</h2><p className="mt-1 text-sm text-slate-500">Controla las opciones disponibles.</p></div><SecondaryButton onClick={() => { const nombre = window.prompt("Nombre del método de pago")?.trim(); if (!nombre) return; if (esDemo) { setMetodos((items) => [...items, { id: `m-${Date.now()}`, nombre, activo: true }]); return; } iniciar(async () => { try { const nuevo = await crearMetodoPagoReal(tallerId, nombre); setMetodos((items) => [...items, nuevo]); setAviso("Método creado correctamente."); } catch (error) { setAviso(error instanceof Error ? error.message : "No se pudo crear el método."); } }); }}><Icon name="plus" className="size-4"/>Agregar</SecondaryButton></div><ul className="divide-y divide-slate-100 dark:divide-slate-800">{metodos.map((metodo) => <li key={metodo.id} className="flex items-center justify-between gap-4 px-5 py-4"><div><p className="font-semibold text-slate-900 dark:text-white">{metodo.nombre}</p><p className="text-xs text-slate-500">{metodo.activo ? "Disponible para pagos nuevos" : "Inactivo"}</p></div><button type="button" role="switch" aria-checked={metodo.activo} aria-label={`${metodo.activo ? "Desactivar" : "Activar"} ${metodo.nombre}`} onClick={() => { if (esDemo) return setMetodos((items) => items.map((item) => item.id === metodo.id ? { ...item, activo: !item.activo } : item)); iniciar(async () => { try { await actualizarMetodoPagoReal(tallerId, metodo.id, { activo: !metodo.activo }); setMetodos((items) => items.map((item) => item.id === metodo.id ? { ...item, activo: !item.activo } : item)); } catch (error) { setAviso(error instanceof Error ? error.message : "No se pudo actualizar el método."); } }); }} className={`relative h-6 w-11 rounded-full transition ${metodo.activo ? "bg-teal-600" : "bg-slate-300 dark:bg-slate-700"}`}><span className={`absolute top-0.5 size-5 rounded-full bg-white shadow transition ${metodo.activo ? "left-[22px]" : "left-0.5"}`}/></button></li>)}</ul></Panel>}
        {seccion === "miembros" && esDueno && <Panel><div className="flex flex-col gap-3 border-b border-slate-200 p-5 dark:border-slate-800 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="font-bold text-slate-950 dark:text-white">Miembros y roles</h2><p className="mt-1 text-sm text-slate-500">Administra acceso al taller.</p></div><PrimaryButton onClick={() => { const usuario = window.prompt("Nombre de usuario existente")?.trim(); if (!usuario) return; const rol = window.prompt("Rol: dueno o tecnico", "tecnico") as components["schemas"]["RolMembresia"]; if (rol !== "dueno" && rol !== "tecnico") return; iniciar(async () => { try { const nuevo = await agregarMiembroReal(tallerId, { nombre_usuario: usuario, rol }); setMiembros((items) => [...items, { id: nuevo.usuario_id, usuarioId: nuevo.usuario_id, rol: nuevo.rol }]); setAviso("Miembro agregado correctamente."); } catch (error) { setAviso(error instanceof Error ? error.message : "No se pudo agregar el miembro."); } }); }}><Icon name="plus" className="size-4"/>Invitar miembro</PrimaryButton></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{miembros.map((miembro) => <div key={miembro.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-slate-900 dark:text-white">{miembro.usuarioId}</p><p className="text-xs text-slate-500">ID de usuario</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{miembro.rol === "dueno" ? "Dueño" : "Técnico"}</span><button type="button" onClick={() => iniciar(async () => { const rol = miembro.rol === "dueno" ? "tecnico" : "dueno"; await cambiarRolMiembroReal(tallerId, miembro.usuarioId, rol); setMiembros((items) => items.map((item) => item.id === miembro.id ? { ...item, rol } : item)); })} className="rounded-lg px-2 py-1 text-xs text-slate-500 hover:bg-slate-100">Cambiar rol</button><button type="button" onClick={() => iniciar(async () => { await retirarMiembroReal(tallerId, miembro.usuarioId); setMiembros((items) => items.filter((item) => item.id !== miembro.id)); })} className="rounded-lg px-2 py-1 text-xs text-red-600 hover:bg-red-50">Retirar</button></div></div>)}</div></Panel>}
      </div></div><p className="sr-only">Configuración del taller {tallerId}. Rol actual: {rolActual}.</p></div>;
}
