"use client";

import { FormEvent, useState } from "react";
import type { RolTaller } from "./types";
import { Icon, PageHeading, Panel, PrimaryButton, SecondaryButton, fieldClass, labelClass } from "./ui";

type Seccion = "taller" | "catalogos" | "pagos" | "miembros";
type Catalogo = { titulo: string; descripcion: string; valores: string[] };

const secciones: { id: Seccion; label: string; icon: "store" | "tag" | "card" | "shield" }[] = [
  { id: "taller", label: "Datos del taller", icon: "store" },
  { id: "catalogos", label: "Catálogos", icon: "tag" },
  { id: "pagos", label: "Métodos de pago", icon: "card" },
  { id: "miembros", label: "Miembros y roles", icon: "shield" },
];

const catalogosIniciales: Catalogo[] = [
  { titulo: "Tipos de equipo", descripcion: "Clasifica los dispositivos que recibes.", valores: ["Celular", "Portátil", "Tablet", "Consola"] },
  { titulo: "Marcas", descripcion: "Marcas disponibles al registrar un equipo.", valores: ["Apple", "Samsung", "Lenovo", "Dell", "Xiaomi"] },
  { titulo: "Tipos de servicio", descripcion: "Servicios reutilizables al cotizar una orden.", valores: ["Diagnóstico", "Cambio de pantalla", "Mantenimiento", "Recuperación de datos"] },
];

export function ConfiguracionPanel({ tallerId, rolActual = "dueno" }: { tallerId: string; rolActual?: RolTaller }) {
  const esDueno = rolActual === "dueno";
  const [seccion, setSeccion] = useState<Seccion>("taller");
  const [catalogos, setCatalogos] = useState(catalogosIniciales);
  const [metodos, setMetodos] = useState([{ id: "m1", nombre: "Efectivo", activo: true }, { id: "m2", nombre: "Transferencia bancaria", activo: true }, { id: "m3", nombre: "Tarjeta", activo: true }, { id: "m4", nombre: "Crédito interno", activo: false }]);
  const [aviso, setAviso] = useState("");

  function guardar(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setAviso("Cambios guardados correctamente."); }
  function agregarValor(indice: number) { const valor = window.prompt(`Nuevo valor para ${catalogos[indice].titulo}`)?.trim(); if (!valor) return; setCatalogos((actuales) => actuales.map((catalogo, i) => i === indice ? { ...catalogo, valores: [...catalogo.valores, valor] } : catalogo)); }

  const navegacion = secciones.filter((item) => item.id !== "miembros" || esDueno);
  return <div className="space-y-6"><PageHeading eyebrow="Administración" title="Configuración" description="Personaliza la información y los catálogos operativos de este taller."/>
    {aviso && <div role="status" className="flex items-center justify-between rounded-xl border border-teal-200 bg-teal-50 px-4 py-3 text-sm text-teal-900 dark:border-teal-800 dark:bg-teal-950/40 dark:text-teal-200"><span>{aviso}</span><button type="button" onClick={() => setAviso("")} aria-label="Ocultar aviso"><Icon name="close" className="size-4"/></button></div>}
    <div className="grid gap-5 lg:grid-cols-[240px_minmax(0,1fr)]"><Panel className="h-fit p-2"><nav aria-label="Secciones de configuración" className="flex gap-1 overflow-x-auto lg:flex-col">{navegacion.map((item) => <button type="button" key={item.id} onClick={() => setSeccion(item.id)} aria-current={seccion === item.id ? "page" : undefined} className={`inline-flex min-w-max items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold transition lg:w-full ${seccion === item.id ? "bg-teal-50 text-teal-800 dark:bg-teal-500/10 dark:text-teal-300" : "text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-slate-800"}`}><Icon name={item.icon} className="size-4"/>{item.label}</button>)}</nav></Panel>
      <div>
        {seccion === "taller" && <Panel><div className="border-b border-slate-200 p-5 dark:border-slate-800"><h2 className="font-bold text-slate-950 dark:text-white">Información del taller</h2><p className="mt-1 text-sm text-slate-500">Estos datos identifican tu operación y aparecen en documentos públicos.</p></div><form onSubmit={guardar} className="space-y-5 p-5"><label className={labelClass}>Nombre comercial *<input className={fieldClass} defaultValue="Taller Central" required/></label><div className="grid gap-4 sm:grid-cols-2"><label className={labelClass}>Identificación fiscal<input className={fieldClass} defaultValue="901.455.220-1"/></label><label className={labelClass}>Teléfono<input className={fieldClass} type="tel" defaultValue="+57 601 555 0190"/></label></div><label className={labelClass}>Dirección<input className={fieldClass} defaultValue="Calle 84 # 18-21"/></label><div className="grid gap-4 sm:grid-cols-3"><label className={labelClass}>País<select className={fieldClass} defaultValue="CO"><option value="CO">Colombia</option><option value="MX">México</option><option value="ES">España</option></select></label><label className={labelClass}>Moneda<select className={fieldClass} defaultValue="COP"><option value="COP">COP — Peso colombiano</option><option value="USD">USD — Dólar</option><option value="MXN">MXN — Peso mexicano</option></select></label><label className={labelClass}>Zona horaria<select className={fieldClass} defaultValue="America/Bogota"><option>America/Bogota</option><option>America/Mexico_City</option><option>Europe/Madrid</option></select></label></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900/70 dark:bg-amber-500/10 dark:text-amber-200"><strong>Importante:</strong> cambiar la moneda solo afecta registros nuevos. Las órdenes existentes conservan la moneda con la que fueron creadas.</div><div className="flex justify-end"><PrimaryButton type="submit">Guardar cambios</PrimaryButton></div></form></Panel>}
        {seccion === "catalogos" && <div className="space-y-4"><div><h2 className="font-bold text-slate-950 dark:text-white">Catálogos operativos</h2><p className="mt-1 text-sm text-slate-500">Los valores inactivos permanecen en el historial, pero no se ofrecen en registros nuevos.</p></div>{catalogos.map((catalogo, indice) => <Panel key={catalogo.titulo} className="p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-bold text-slate-900 dark:text-white">{catalogo.titulo}</h3><p className="mt-1 text-sm text-slate-500">{catalogo.descripcion}</p></div><SecondaryButton onClick={() => agregarValor(indice)}><Icon name="plus" className="size-4"/>Agregar</SecondaryButton></div><div className="mt-4 flex flex-wrap gap-2">{catalogo.valores.map((valor) => <span key={valor} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-700 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200">{valor}<button type="button" aria-label={`Editar ${valor}`} className="text-slate-400 hover:text-teal-600"><Icon name="edit" className="size-3.5"/></button></span>)}</div></Panel>)}</div>}
        {seccion === "pagos" && <Panel><div className="flex items-start justify-between gap-3 border-b border-slate-200 p-5 dark:border-slate-800"><div><h2 className="font-bold text-slate-950 dark:text-white">Métodos de pago</h2><p className="mt-1 text-sm text-slate-500">Controla las opciones disponibles al registrar pagos.</p></div><SecondaryButton onClick={() => { const nombre = window.prompt("Nombre del método de pago")?.trim(); if (nombre) setMetodos((items) => [...items, { id: `m-${Date.now()}`, nombre, activo: true }]); }}><Icon name="plus" className="size-4"/>Agregar</SecondaryButton></div><ul className="divide-y divide-slate-100 dark:divide-slate-800">{metodos.map((metodo) => <li key={metodo.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"><Icon name="card" className="size-4"/></span><div><p className="font-semibold text-slate-900 dark:text-white">{metodo.nombre}</p><p className="text-xs text-slate-500">{metodo.activo ? "Disponible para pagos nuevos" : "Inactivo"}</p></div></div><button type="button" role="switch" aria-checked={metodo.activo} aria-label={`${metodo.activo ? "Desactivar" : "Activar"} ${metodo.nombre}`} onClick={() => setMetodos((items) => items.map((item) => item.id === metodo.id ? { ...item, activo: !item.activo } : item))} className={`relative h-6 w-11 rounded-full transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500 ${metodo.activo ? "bg-teal-600" : "bg-slate-300 dark:bg-slate-700"}`}><span className={`absolute top-0.5 size-5 rounded-full bg-white shadow transition ${metodo.activo ? "left-[22px]" : "left-0.5"}`}/></button></li>)}</ul></Panel>}
        {seccion === "miembros" && esDueno && <Panel><div className="flex flex-col gap-3 border-b border-slate-200 p-5 dark:border-slate-800 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="font-bold text-slate-950 dark:text-white">Miembros y roles</h2><p className="mt-1 text-sm text-slate-500">Solo los dueños pueden invitar personas o cambiar sus roles.</p></div><PrimaryButton><Icon name="plus" className="size-4"/>Invitar miembro</PrimaryButton></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{[{ nombre: "Isabella G", correo: "Isabella@tallercentral.co", rol: "Dueño", iniciales: "IG", actual: true }, { nombre: "Mateo Rodríguez", correo: "mateo@tallercentral.co", rol: "Técnico", iniciales: "MR" }, { nombre: "Isabella Castro", correo: "isabella.castro@tallercentral.co", rol: "Técnico", iniciales: "IC" }].map((miembro) => <div key={miembro.correo} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-teal-100 text-sm font-bold text-teal-800 dark:bg-teal-500/15 dark:text-teal-300">{miembro.iniciales}</span><div><p className="font-semibold text-slate-900 dark:text-white">{miembro.nombre}{miembro.actual && <span className="ml-2 text-xs font-normal text-slate-400">Tú</span>}</p><p className="text-xs text-slate-500">{miembro.correo}</p></div></div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{miembro.rol}</span>{!miembro.actual && <button type="button" aria-label={`Opciones de ${miembro.nombre}`} className="rounded-lg px-2 py-1 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800">•••</button>}</div></div>)}</div></Panel>}
      </div></div><p className="sr-only">Configuración del taller {tallerId}. Rol actual: {rolActual}.</p></div>;
}

