"use client";

import { FormEvent, useMemo, useState } from "react";
import type { Proveedor } from "./types";
import { EmptyState, Icon, Modal, PageHeading, Panel, PrimaryButton, SearchField, SecondaryButton, fieldClass, labelClass } from "./ui";

const proveedoresIniciales: Proveedor[] = [
  { id: "pro-1", nombre: "TecnoPartes Colombia", identificacion: "901.224.810-3", contacto: "Diana Cárdenas", telefono: "+57 320 410 8821", correo: "ventas@tecnopartes.co", ciudad: "Bogotá", activo: true, repuestos: 24, ultimaEntrada: "6 ago 2026" },
  { id: "pro-2", nombre: "Mundo Móvil SAS", identificacion: "900.811.020-7", contacto: "Felipe Torres", telefono: "+57 316 300 5520", correo: "pedidos@mundomovil.co", ciudad: "Medellín", activo: true, repuestos: 18, ultimaEntrada: "2 ago 2026" },
  { id: "pro-3", nombre: "CompuSupply", identificacion: "830.123.772-1", contacto: "Isabella G", telefono: "+57 601 518 3009", correo: "comercial@compusupply.com", ciudad: "Bogotá", activo: true, repuestos: 11, ultimaEntrada: "18 jul 2026" },
  { id: "pro-4", nombre: "Importaciones Nova", identificacion: "901.018.442-8", contacto: "Andrés León", telefono: "+57 300 991 4100", ciudad: "Cali", activo: false, repuestos: 4, ultimaEntrada: "9 feb 2026" },
];

export function ProveedoresPanel({ tallerId, initialProveedores = proveedoresIniciales }: { tallerId: string; initialProveedores?: Proveedor[] }) {
  const [proveedores, setProveedores] = useState(initialProveedores);
  const [consulta, setConsulta] = useState("");
  const [estado, setEstado] = useState<"activos" | "todos">("activos");
  const [seleccionadoId, setSeleccionadoId] = useState(initialProveedores[0]?.id ?? "");
  const [modal, setModal] = useState(false);
  const [confirmar, setConfirmar] = useState(false);
  const filtrados = useMemo(() => proveedores.filter((proveedor) => `${proveedor.nombre} ${proveedor.identificacion ?? ""} ${proveedor.contacto ?? ""} ${proveedor.ciudad ?? ""}`.toLowerCase().includes(consulta.toLowerCase()) && (estado === "todos" || proveedor.activo)), [proveedores, consulta, estado]);
  const seleccionado = proveedores.find((item) => item.id === seleccionadoId);

  function crear(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const nuevo: Proveedor = { id: `pro-${Date.now()}`, nombre: String(data.get("nombre")), identificacion: String(data.get("identificacion") || ""), contacto: String(data.get("contacto") || ""), telefono: String(data.get("telefono") || ""), correo: String(data.get("correo") || ""), ciudad: String(data.get("ciudad") || ""), activo: true, repuestos: 0 }; setProveedores((items) => [nuevo, ...items]); setSeleccionadoId(nuevo.id); setModal(false); }
  function alternarEstado() { if (!seleccionado) return; setProveedores((items) => items.map((item) => item.id === seleccionado.id ? { ...item, activo: !item.activo } : item)); setConfirmar(false); }

  return <div className="space-y-6"><PageHeading eyebrow="Abastecimiento" title="Proveedores" description="Mantén al día los contactos y referencias de quienes abastecen tu inventario." action={<PrimaryButton onClick={() => setModal(true)}><Icon name="plus" className="size-4"/>Nuevo proveedor</PrimaryButton>}/>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(320px,.75fr)]"><Panel className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-200 p-4 dark:border-slate-800 sm:flex-row"><SearchField value={consulta} onChange={setConsulta} placeholder="Nombre, NIT, contacto o ciudad"/><select aria-label="Filtrar proveedores por estado" value={estado} onChange={(event) => setEstado(event.target.value as "activos" | "todos")} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none focus:border-teal-500 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200"><option value="activos">Solo activos</option><option value="todos">Todos</option></select></div>{filtrados.length === 0 ? <EmptyState icon="truck" title="No hay proveedores" description="Cambia el filtro o registra un nuevo contacto."/> : <div className="divide-y divide-slate-100 dark:divide-slate-800">{filtrados.map((proveedor) => <button type="button" key={proveedor.id} onClick={() => setSeleccionadoId(proveedor.id)} className={`grid w-full gap-2 px-4 py-4 text-left transition hover:bg-slate-50 dark:hover:bg-slate-800/50 sm:grid-cols-[minmax(0,1fr)_140px_100px] sm:items-center ${proveedor.id === seleccionadoId ? "bg-teal-50/70 dark:bg-teal-950/25" : ""}`}><div className="flex min-w-0 items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"><Icon name="truck" className="size-5"/></span><div className="min-w-0"><p className="truncate font-semibold text-slate-900 dark:text-white">{proveedor.nombre}</p><p className="truncate text-xs text-slate-500">{proveedor.contacto || "Sin contacto"} · {proveedor.telefono || "Sin teléfono"}</p></div></div><span className="text-xs text-slate-500 sm:text-right">{proveedor.ciudad || "Sin ciudad"}<br/>{proveedor.ultimaEntrada ? `Última entrada: ${proveedor.ultimaEntrada}` : "Sin entradas"}</span><span className={`justify-self-start rounded-full px-2 py-1 text-xs font-semibold sm:justify-self-end ${proveedor.activo ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-500/15 dark:text-emerald-300" : "bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400"}`}>{proveedor.activo ? "Activo" : "Inactivo"}</span></button>)}</div>}</Panel>
      <Panel className="h-fit overflow-hidden">{!seleccionado ? <EmptyState icon="truck" title="Selecciona un proveedor" description="Consulta aquí su información de contacto."/> : <><div className="border-b border-slate-200 p-5 dark:border-slate-800"><div className="flex items-start justify-between gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-teal-100 text-teal-700 dark:bg-teal-500/15 dark:text-teal-300"><Icon name="store" className="size-6"/></span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${seleccionado.activo ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-500/15 dark:text-emerald-300" : "bg-slate-100 text-slate-500 dark:bg-slate-800"}`}>{seleccionado.activo ? "Activo" : "Inactivo"}</span></div><h2 className="mt-4 text-lg font-bold text-slate-950 dark:text-white">{seleccionado.nombre}</h2><p className="text-sm text-slate-500">NIT {seleccionado.identificacion || "no registrado"}</p></div><dl className="space-y-4 p-5 text-sm"><div><dt className="text-xs font-medium uppercase tracking-wide text-slate-400">Contacto</dt><dd className="mt-1 font-medium text-slate-800 dark:text-slate-100">{seleccionado.contacto || "Sin registrar"}</dd></div><div className="grid grid-cols-2 gap-3"><div><dt className="text-xs font-medium uppercase tracking-wide text-slate-400">Teléfono</dt><dd className="mt-1 text-slate-700 dark:text-slate-200">{seleccionado.telefono || "—"}</dd></div><div><dt className="text-xs font-medium uppercase tracking-wide text-slate-400">Ciudad</dt><dd className="mt-1 text-slate-700 dark:text-slate-200">{seleccionado.ciudad || "—"}</dd></div></div><div><dt className="text-xs font-medium uppercase tracking-wide text-slate-400">Correo</dt><dd className="mt-1 break-all text-slate-700 dark:text-slate-200">{seleccionado.correo || "—"}</dd></div><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800/60"><dt className="text-xs text-slate-500">Referencias asociadas</dt><dd className="mt-1 text-xl font-bold text-slate-900 dark:text-white">{seleccionado.repuestos}</dd></div></dl><div className="flex gap-2 border-t border-slate-200 p-5 dark:border-slate-800"><SecondaryButton className="flex-1"><Icon name="edit" className="size-4"/>Editar</SecondaryButton><button type="button" onClick={() => setConfirmar(true)} className={`flex-1 rounded-xl border px-3 py-2 text-sm font-semibold ${seleccionado.activo ? "border-red-200 text-red-700 hover:bg-red-50 dark:border-red-900 dark:text-red-300" : "border-emerald-200 text-emerald-700 hover:bg-emerald-50 dark:border-emerald-900 dark:text-emerald-300"}`}>{seleccionado.activo ? "Desactivar" : "Reactivar"}</button></div></>}</Panel></div>
    {modal && <Modal title="Nuevo proveedor" description="Registra la información necesaria para compras y entradas." onClose={() => setModal(false)}><form onSubmit={crear} className="space-y-4"><label className={labelClass}>Nombre o razón social *<input name="nombre" required autoFocus className={fieldClass}/></label><div className="grid gap-4 sm:grid-cols-2"><label className={labelClass}>NIT<input name="identificacion" className={fieldClass}/></label><label className={labelClass}>Ciudad<input name="ciudad" className={fieldClass}/></label></div><label className={labelClass}>Persona de contacto<input name="contacto" className={fieldClass}/></label><div className="grid gap-4 sm:grid-cols-2"><label className={labelClass}>Teléfono<input name="telefono" type="tel" className={fieldClass}/></label><label className={labelClass}>Correo<input name="correo" type="email" className={fieldClass}/></label></div><div className="flex justify-end gap-2"><SecondaryButton type="button" onClick={() => setModal(false)}>Cancelar</SecondaryButton><PrimaryButton type="submit">Guardar proveedor</PrimaryButton></div></form></Modal>}
    {confirmar && seleccionado && <Modal title={seleccionado.activo ? "Desactivar proveedor" : "Reactivar proveedor"} description={seleccionado.activo ? "Dejará de aparecer en selecciones nuevas, pero conservarás su historial." : "Volverá a estar disponible para entradas y repuestos."} onClose={() => setConfirmar(false)}><div className="flex justify-end gap-2"><SecondaryButton onClick={() => setConfirmar(false)}>Cancelar</SecondaryButton><PrimaryButton onClick={alternarEstado}>Confirmar</PrimaryButton></div></Modal>}
    <p className="sr-only">Taller activo: {tallerId}</p></div>;
}

